version = "1.0"

[server]
bind = "0.0.0.0:8080"
admin_bind = "127.0.0.1:9090"
graceful_shutdown_ms = 5000

[logging]
level = "info"
format = "json"
output = "stdout"

[wasm]
runtime = "wazero"
cache_dir = "./cache/wasm"
max_modules = 64

# -------------------------
# WAF inline mode (config + request send at each call/request)
# -------------------------
[[modules]]
id = "waf"
enabled = true
path = "./modules/scloud-eg-waf/target/wasm32-wasip1/release/scloud_eg_waf.wasm"
route = "/"
timeout_ms = 200

config_mode = "inline"   # "init" | "inline"

# (optionnels)
# entry_fn = "handle"
# alloc_fn = "alloc"
# init_fn  = "init"

  [modules.config]
  mode = "block"
  rules_path = "/etc/edge/rules.json"
  log = true

# -------------------------
# RateLimit init mode (config injected at init, request without config sent at each call)
# -------------------------
[[modules]]
id = "ratelimit"
enabled = true
path = "./modules/scloud-eg-rate-limit/target/wasm32-wasip1/release/scloud_eg_rate_limit.wasm"
route = "/rate-limit"
timeout_ms = 50

config_mode = "init"

# (optionnal)
# entry_fn = "handle"
# alloc_fn = "alloc"
# init_fn  = "init"

  [modules.config]
  algorithm = "token_bucket"
  rps = 100
  burst = 200
  key = "ip"
